services:
  app:
    container_name: grocereach-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    container_name: grocereach-db
    image: 'postgres:17.2'
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  redis:
    container_name: grocereach-redis
    image: 'redis:7.4'
    ports:
      - '6379:6379'

volumes:
  postgres_data: